/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.bicilceta;

import cl.duoc.controladores.controladorUsuario;
import cl.duoc.entidades.Usuario;
import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author DarkShoot3r
 */
public class Menu extends javax.swing.JFrame {

    private controladorUsuario cu = new controladorUsuario();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        inicioApp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        Frame_IniciarSesion = new javax.swing.JInternalFrame();
        jLabelInicioSesionUsuario = new javax.swing.JLabel();
        jLabelIniciarSesionPassword = new javax.swing.JLabel();
        jTextFieldIniciarSesionUsuario = new javax.swing.JTextField();
        jButtonIniciarSesionLogin = new javax.swing.JButton();
        jPasswordFieldIniciarSesionPassword = new javax.swing.JPasswordField();
        Frame_ListaFabricantes = new javax.swing.JInternalFrame();
        jLabelIdFabricantes = new javax.swing.JLabel();
        jTextFieldIdFabricantes = new javax.swing.JTextField();
        jLabelIdNombreFabricante = new javax.swing.JLabel();
        jTextFieldIdNombreFabricantes = new javax.swing.JTextField();
        jButtonAgregarFabricantes = new javax.swing.JButton();
        jButtonEliminarFabricantes = new javax.swing.JButton();
        jButtonModificarFabricantes = new javax.swing.JButton();
        jButtonLimpiarFabricantes = new javax.swing.JButton();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_RegistarFabricantees = new javax.swing.JTable();
        Frame_EditarFabricantes = new javax.swing.JInternalFrame();
        Frame_EditarCategorias = new javax.swing.JInternalFrame();
        Frame_acercaDe = new javax.swing.JInternalFrame();
        Frame_EditarBicicletas = new javax.swing.JInternalFrame();
        Frame_ListarBicicletas = new javax.swing.JInternalFrame();
        jLabelIdCategoría1 = new javax.swing.JLabel();
        jTextFieldIdCategoría1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabla_RegistarBicicletaas = new javax.swing.JTable();
        jLabelNombreCategoría1 = new javax.swing.JLabel();
        jTextFieldNombreCategoría1 = new javax.swing.JTextField();
        jButtonAgregarCategoría1 = new javax.swing.JButton();
        jButtonModificarCategoría1 = new javax.swing.JButton();
        jButtonEliminarCategoría1 = new javax.swing.JButton();
        jButtonLimpiarCategoría1 = new javax.swing.JButton();
        Frame_ListarCategorias = new javax.swing.JInternalFrame();
        jLabel_IngresdeID_Categorias = new javax.swing.JLabel();
        jTextFieldIdCategoría = new javax.swing.JTextField();
        jLabelNombreCategoría = new javax.swing.JLabel();
        jTextFieldNombreCategoría = new javax.swing.JTextField();
        jButtonAgregarCategoría = new javax.swing.JButton();
        jButtonModificarCategoría = new javax.swing.JButton();
        jButtonEliminarCategoría = new javax.swing.JButton();
        jButtonLimpiarCategoría = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_RegistarCategoriaas = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        MENU_PERFIL = new javax.swing.JMenu();
        Menu_IniciarSesion = new javax.swing.JMenuItem();
        Menu_CerrarSesion = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Menu_Salir = new javax.swing.JMenuItem();
        Menu_Categorias = new javax.swing.JMenu();
        jMenu_Fabricantes = new javax.swing.JMenu();
        jMenu_ListaFabricantes = new javax.swing.JMenuItem();
        jMenu_Mfabricantes = new javax.swing.JMenuItem();
        jMenu_Categorias = new javax.swing.JMenu();
        Menu_ListarCategorias = new javax.swing.JMenuItem();
        jMenu_Mcategoria = new javax.swing.JMenuItem();
        jMenu_Bicicletas = new javax.swing.JMenu();
        Menu_ListarBicilcetas = new javax.swing.JMenuItem();
        jMenu_Mbicicletas = new javax.swing.JMenuItem();
        Menu_Ayuda = new javax.swing.JMenu();
        Menu_AcercaDe = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Frame_IniciarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Frame_IniciarSesion.setClosable(true);
        Frame_IniciarSesion.setMaximizable(true);
        Frame_IniciarSesion.setTitle("Iniciar Sesion");
        Frame_IniciarSesion.setVisible(true);
        Frame_IniciarSesion.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Frame_IniciarSesionAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Frame_IniciarSesion.getContentPane().setLayout(null);

        jLabelInicioSesionUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelInicioSesionUsuario.setText("Usuario: ");
        Frame_IniciarSesion.getContentPane().add(jLabelInicioSesionUsuario);
        jLabelInicioSesionUsuario.setBounds(20, 30, 140, 50);

        jLabelIniciarSesionPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelIniciarSesionPassword.setText("Password: ");
        Frame_IniciarSesion.getContentPane().add(jLabelIniciarSesionPassword);
        jLabelIniciarSesionPassword.setBounds(20, 90, 110, 40);

        jTextFieldIniciarSesionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIniciarSesionUsuarioActionPerformed(evt);
            }
        });
        Frame_IniciarSesion.getContentPane().add(jTextFieldIniciarSesionUsuario);
        jTextFieldIniciarSesionUsuario.setBounds(100, 46, 170, 19);

        jButtonIniciarSesionLogin.setText("Ingresar");
        jButtonIniciarSesionLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionLoginActionPerformed(evt);
            }
        });
        Frame_IniciarSesion.getContentPane().add(jButtonIniciarSesionLogin);
        jButtonIniciarSesionLogin.setBounds(100, 160, 110, 50);

        jPasswordFieldIniciarSesionPassword.setEchoChar('\u25cf');
        jPasswordFieldIniciarSesionPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldIniciarSesionPasswordActionPerformed(evt);
            }
        });
        Frame_IniciarSesion.getContentPane().add(jPasswordFieldIniciarSesionPassword);
        jPasswordFieldIniciarSesionPassword.setBounds(100, 100, 170, 30);

        getContentPane().add(Frame_IniciarSesion);
        Frame_IniciarSesion.setBounds(30, 20, 310, 310);

        Frame_ListaFabricantes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Frame_ListaFabricantes.setClosable(true);
        Frame_ListaFabricantes.setMaximizable(true);
        Frame_ListaFabricantes.setResizable(true);
        Frame_ListaFabricantes.setTitle("Registrar Fabricantes");
        Frame_ListaFabricantes.setVisible(true);

        jLabelIdFabricantes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelIdFabricantes.setText("Ingrese ID:");

        jTextFieldIdFabricantes.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldIdFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdFabricantesActionPerformed(evt);
            }
        });

        jLabelIdNombreFabricante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelIdNombreFabricante.setText("Nombre:");

        jTextFieldIdNombreFabricantes.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldIdNombreFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdNombreFabricantesActionPerformed(evt);
            }
        });

        jButtonAgregarFabricantes.setText("AGREGAR");
        jButtonAgregarFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarFabricantesActionPerformed(evt);
            }
        });

        jButtonEliminarFabricantes.setText("ELIMINAR");

        jButtonModificarFabricantes.setText("MODIFICAR");

        jButtonLimpiarFabricantes.setText("LIMPIAR");

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });

        Tabla_RegistarFabricantees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabla_RegistarFabricantees);

        javax.swing.GroupLayout Frame_ListaFabricantesLayout = new javax.swing.GroupLayout(Frame_ListaFabricantes.getContentPane());
        Frame_ListaFabricantes.getContentPane().setLayout(Frame_ListaFabricantesLayout);
        Frame_ListaFabricantesLayout.setHorizontalGroup(
            Frame_ListaFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_ListaFabricantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Frame_ListaFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Frame_ListaFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Frame_ListaFabricantesLayout.createSequentialGroup()
                            .addComponent(jLabelIdFabricantes)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldIdFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Frame_ListaFabricantesLayout.createSequentialGroup()
                            .addComponent(jLabelIdNombreFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldIdNombreFabricantes)))
                    .addGroup(Frame_ListaFabricantesLayout.createSequentialGroup()
                        .addGroup(Frame_ListaFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Frame_ListaFabricantesLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(Frame_ListaFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonModificarFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAgregarFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(Frame_ListaFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonEliminarFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonLimpiarFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22)))
                .addGap(64, 64, 64))
            .addGroup(Frame_ListaFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Frame_ListaFabricantesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Frame_ListaFabricantesLayout.setVerticalGroup(
            Frame_ListaFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_ListaFabricantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Frame_ListaFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIdFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Frame_ListaFabricantesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldIdFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Frame_ListaFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdNombreFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIdNombreFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Frame_ListaFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAgregarFabricantes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEliminarFabricantes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Frame_ListaFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpiarFabricantes)
                    .addComponent(jButtonModificarFabricantes))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(Frame_ListaFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Frame_ListaFabricantesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(Frame_ListaFabricantes);
        Frame_ListaFabricantes.setBounds(450, 30, 320, 360);

        Frame_EditarFabricantes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Frame_EditarFabricantes.setClosable(true);
        Frame_EditarFabricantes.setMaximizable(true);
        Frame_EditarFabricantes.setTitle("Editar Fabricantes");
        Frame_EditarFabricantes.setVisible(true);

        javax.swing.GroupLayout Frame_EditarFabricantesLayout = new javax.swing.GroupLayout(Frame_EditarFabricantes.getContentPane());
        Frame_EditarFabricantes.getContentPane().setLayout(Frame_EditarFabricantesLayout);
        Frame_EditarFabricantesLayout.setHorizontalGroup(
            Frame_EditarFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
        Frame_EditarFabricantesLayout.setVerticalGroup(
            Frame_EditarFabricantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        getContentPane().add(Frame_EditarFabricantes);
        Frame_EditarFabricantes.setBounds(850, 840, 220, 220);

        Frame_EditarCategorias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Frame_EditarCategorias.setClosable(true);
        Frame_EditarCategorias.setMaximizable(true);
        Frame_EditarCategorias.setTitle("Editar Categorias");
        Frame_EditarCategorias.setVisible(true);

        Frame_acercaDe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Frame_acercaDe.setClosable(true);
        Frame_acercaDe.setMaximizable(true);
        Frame_acercaDe.setTitle("Acerca de");
        Frame_acercaDe.setVisible(true);

        Frame_EditarBicicletas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Frame_EditarBicicletas.setClosable(true);
        Frame_EditarBicicletas.setMaximizable(true);
        Frame_EditarBicicletas.setTitle("Editar Bicicletas");
        Frame_EditarBicicletas.setToolTipText("");
        Frame_EditarBicicletas.setVisible(true);

        javax.swing.GroupLayout Frame_EditarBicicletasLayout = new javax.swing.GroupLayout(Frame_EditarBicicletas.getContentPane());
        Frame_EditarBicicletas.getContentPane().setLayout(Frame_EditarBicicletasLayout);
        Frame_EditarBicicletasLayout.setHorizontalGroup(
            Frame_EditarBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        Frame_EditarBicicletasLayout.setVerticalGroup(
            Frame_EditarBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Frame_acercaDeLayout = new javax.swing.GroupLayout(Frame_acercaDe.getContentPane());
        Frame_acercaDe.getContentPane().setLayout(Frame_acercaDeLayout);
        Frame_acercaDeLayout.setHorizontalGroup(
            Frame_acercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_acercaDeLayout.createSequentialGroup()
                .addComponent(Frame_EditarBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Frame_acercaDeLayout.setVerticalGroup(
            Frame_acercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Frame_acercaDeLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(Frame_EditarBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Frame_EditarCategoriasLayout = new javax.swing.GroupLayout(Frame_EditarCategorias.getContentPane());
        Frame_EditarCategorias.getContentPane().setLayout(Frame_EditarCategoriasLayout);
        Frame_EditarCategoriasLayout.setHorizontalGroup(
            Frame_EditarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Frame_EditarCategoriasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Frame_acercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Frame_EditarCategoriasLayout.setVerticalGroup(
            Frame_EditarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Frame_EditarCategoriasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Frame_acercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(Frame_EditarCategorias);
        Frame_EditarCategorias.setBounds(830, 710, 278, 340);

        Frame_ListarBicicletas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Frame_ListarBicicletas.setClosable(true);
        Frame_ListarBicicletas.setMaximizable(true);
        Frame_ListarBicicletas.setTitle("Registrar Bicicletas");
        Frame_ListarBicicletas.setVisible(true);

        jLabelIdCategoría1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelIdCategoría1.setText("Ingrese ID:");

        jTextFieldIdCategoría1.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldIdCategoría1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdCategoría1ActionPerformed(evt);
            }
        });
        jTextFieldIdCategoría1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIdCategoría1KeyTyped(evt);
            }
        });

        Tabla_RegistarBicicletaas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(Tabla_RegistarBicicletaas);

        jLabelNombreCategoría1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNombreCategoría1.setText("Nombre:");

        jTextFieldNombreCategoría1.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldNombreCategoría1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreCategoría1KeyTyped(evt);
            }
        });

        jButtonAgregarCategoría1.setText("AGREGAR");
        jButtonAgregarCategoría1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarCategoría1ActionPerformed(evt);
            }
        });

        jButtonModificarCategoría1.setText("MODIFICAR");

        jButtonEliminarCategoría1.setText("ELIMINAR");

        jButtonLimpiarCategoría1.setText("LIMPIAR");
        jButtonLimpiarCategoría1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarCategoría1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Frame_ListarBicicletasLayout = new javax.swing.GroupLayout(Frame_ListarBicicletas.getContentPane());
        Frame_ListarBicicletas.getContentPane().setLayout(Frame_ListarBicicletasLayout);
        Frame_ListarBicicletasLayout.setHorizontalGroup(
            Frame_ListarBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_ListarBicicletasLayout.createSequentialGroup()
                .addGroup(Frame_ListarBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Frame_ListarBicicletasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Frame_ListarBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIdCategoría1)
                            .addComponent(jLabelNombreCategoría1))
                        .addGap(37, 37, 37)
                        .addGroup(Frame_ListarBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIdCategoría1)
                            .addComponent(jTextFieldNombreCategoría1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Frame_ListarBicicletasLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Frame_ListarBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Frame_ListarBicicletasLayout.createSequentialGroup()
                                .addGroup(Frame_ListarBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAgregarCategoría1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonModificarCategoría1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addGroup(Frame_ListarBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonLimpiarCategoría1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEliminarCategoría1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(21, 21, 21))
        );
        Frame_ListarBicicletasLayout.setVerticalGroup(
            Frame_ListarBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_ListarBicicletasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Frame_ListarBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdCategoría1)
                    .addComponent(jTextFieldIdCategoría1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Frame_ListarBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreCategoría1)
                    .addComponent(jTextFieldNombreCategoría1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Frame_ListarBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarCategoría1)
                    .addComponent(jButtonEliminarCategoría1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Frame_ListarBicicletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModificarCategoría1)
                    .addComponent(jButtonLimpiarCategoría1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Frame_ListarBicicletas);
        Frame_ListarBicicletas.setBounds(340, 430, 310, 320);

        Frame_ListarCategorias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Frame_ListarCategorias.setClosable(true);
        Frame_ListarCategorias.setMaximizable(true);
        Frame_ListarCategorias.setTitle("Registrar Categorias");
        Frame_ListarCategorias.setVisible(true);

        jLabel_IngresdeID_Categorias.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_IngresdeID_Categorias.setText("Ingrese ID:");

        jTextFieldIdCategoría.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldIdCategoría.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdCategoríaActionPerformed(evt);
            }
        });
        jTextFieldIdCategoría.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIdCategoríaKeyTyped(evt);
            }
        });

        jLabelNombreCategoría.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNombreCategoría.setText("Nombre:");

        jTextFieldNombreCategoría.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldNombreCategoría.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreCategoríaKeyTyped(evt);
            }
        });

        jButtonAgregarCategoría.setText("AGREGAR");
        jButtonAgregarCategoría.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarCategoríaActionPerformed(evt);
            }
        });

        jButtonModificarCategoría.setText("MODIFICAR");

        jButtonEliminarCategoría.setText("ELIMINAR");

        jButtonLimpiarCategoría.setText("LIMPIAR");
        jButtonLimpiarCategoría.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarCategoríaActionPerformed(evt);
            }
        });

        Tabla_RegistarCategoriaas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Tabla_RegistarCategoriaas);

        javax.swing.GroupLayout Frame_ListarCategoriasLayout = new javax.swing.GroupLayout(Frame_ListarCategorias.getContentPane());
        Frame_ListarCategorias.getContentPane().setLayout(Frame_ListarCategoriasLayout);
        Frame_ListarCategoriasLayout.setHorizontalGroup(
            Frame_ListarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_ListarCategoriasLayout.createSequentialGroup()
                .addGroup(Frame_ListarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Frame_ListarCategoriasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Frame_ListarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_IngresdeID_Categorias)
                            .addComponent(jLabelNombreCategoría))
                        .addGap(37, 37, 37)
                        .addGroup(Frame_ListarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIdCategoría)
                            .addComponent(jTextFieldNombreCategoría)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Frame_ListarCategoriasLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Frame_ListarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Frame_ListarCategoriasLayout.createSequentialGroup()
                                .addGroup(Frame_ListarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAgregarCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonModificarCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addGroup(Frame_ListarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonLimpiarCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEliminarCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(21, 21, 21))
        );
        Frame_ListarCategoriasLayout.setVerticalGroup(
            Frame_ListarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_ListarCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Frame_ListarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_IngresdeID_Categorias)
                    .addComponent(jTextFieldIdCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Frame_ListarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreCategoría)
                    .addComponent(jTextFieldNombreCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Frame_ListarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarCategoría)
                    .addComponent(jButtonEliminarCategoría))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Frame_ListarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModificarCategoría)
                    .addComponent(jButtonLimpiarCategoría))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(Frame_ListarCategorias);
        Frame_ListarCategorias.setBounds(0, 430, 320, 322);

        MENU_PERFIL.setText("Perfil");
        MENU_PERFIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_PERFILActionPerformed(evt);
            }
        });

        Menu_IniciarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        Menu_IniciarSesion.setText("Iniciar Sesion ");
        Menu_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_IniciarSesionActionPerformed(evt);
            }
        });
        MENU_PERFIL.add(Menu_IniciarSesion);

        Menu_CerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        Menu_CerrarSesion.setText("Cerrar Sesion");
        MENU_PERFIL.add(Menu_CerrarSesion);
        MENU_PERFIL.add(jSeparator1);

        Menu_Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Menu_Salir.setText("Salir");
        Menu_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_SalirActionPerformed(evt);
            }
        });
        MENU_PERFIL.add(Menu_Salir);

        jMenuBar1.add(MENU_PERFIL);

        Menu_Categorias.setText("Categorias");

        jMenu_Fabricantes.setText("Fabricantes");

        jMenu_ListaFabricantes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenu_ListaFabricantes.setText("Lista Fabricantes");
        jMenu_ListaFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_ListaFabricantesActionPerformed(evt);
            }
        });
        jMenu_Fabricantes.add(jMenu_ListaFabricantes);

        jMenu_Mfabricantes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenu_Mfabricantes.setText("Editar datos");
        jMenu_Mfabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_MfabricantesActionPerformed(evt);
            }
        });
        jMenu_Fabricantes.add(jMenu_Mfabricantes);

        Menu_Categorias.add(jMenu_Fabricantes);

        jMenu_Categorias.setText("Categorias");

        Menu_ListarCategorias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        Menu_ListarCategorias.setText("Listar Categorias");
        Menu_ListarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ListarCategoriasActionPerformed(evt);
            }
        });
        jMenu_Categorias.add(Menu_ListarCategorias);

        jMenu_Mcategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        jMenu_Mcategoria.setText("Editar datos");
        jMenu_Mcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_McategoriaActionPerformed(evt);
            }
        });
        jMenu_Categorias.add(jMenu_Mcategoria);

        Menu_Categorias.add(jMenu_Categorias);

        jMenu_Bicicletas.setText("Bicicletas");

        Menu_ListarBicilcetas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        Menu_ListarBicilcetas.setText("Listar Bicicletas");
        Menu_ListarBicilcetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ListarBicilcetasActionPerformed(evt);
            }
        });
        jMenu_Bicicletas.add(Menu_ListarBicilcetas);

        jMenu_Mbicicletas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenu_Mbicicletas.setText("Editar datos");
        jMenu_Mbicicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_MbicicletasActionPerformed(evt);
            }
        });
        jMenu_Bicicletas.add(jMenu_Mbicicletas);

        Menu_Categorias.add(jMenu_Bicicletas);

        jMenuBar1.add(Menu_Categorias);

        Menu_Ayuda.setText("Ayuda");

        Menu_AcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        Menu_AcercaDe.setText("Acerca de");
        Menu_AcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_AcercaDeActionPerformed(evt);
            }
        });
        Menu_Ayuda.add(Menu_AcercaDe);

        jMenuBar1.add(Menu_Ayuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_ListaFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_ListaFabricantesActionPerformed
        this.Frame_ListaFabricantes.setVisible(true);
    }//GEN-LAST:event_jMenu_ListaFabricantesActionPerformed

    private void Frame_IniciarSesionAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Frame_IniciarSesionAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Frame_IniciarSesionAncestorAdded

    private void MENU_PERFILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_PERFILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MENU_PERFILActionPerformed

    private void Menu_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_Menu_SalirActionPerformed

    private void jMenu_MfabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_MfabricantesActionPerformed
        this.Frame_EditarFabricantes.setVisible(true);
    }//GEN-LAST:event_jMenu_MfabricantesActionPerformed

    private void Menu_ListarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ListarCategoriasActionPerformed
        this.Frame_ListarCategorias.setVisible(true);
    }//GEN-LAST:event_Menu_ListarCategoriasActionPerformed

    private void jMenu_McategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_McategoriaActionPerformed
        this.Frame_EditarCategorias.setVisible(true);
    }//GEN-LAST:event_jMenu_McategoriaActionPerformed

    private void Menu_ListarBicilcetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ListarBicilcetasActionPerformed
        this.Frame_ListarBicicletas.setVisible(true);
    }//GEN-LAST:event_Menu_ListarBicilcetasActionPerformed

    private void jMenu_MbicicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_MbicicletasActionPerformed
        this.Frame_EditarBicicletas.setVisible(true);
    }//GEN-LAST:event_jMenu_MbicicletasActionPerformed

    private void Menu_AcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_AcercaDeActionPerformed
        this.Frame_acercaDe.setVisible(true);
    }//GEN-LAST:event_Menu_AcercaDeActionPerformed

    private void jTextFieldIdCategoríaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdCategoríaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdCategoríaActionPerformed

    private void jButtonAgregarCategoríaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarCategoríaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarCategoríaActionPerformed

    private void jButtonLimpiarCategoríaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarCategoríaActionPerformed
        limpiarFormularioRegistroCategorias();
    }//GEN-LAST:event_jButtonLimpiarCategoríaActionPerformed

    private void jTextFieldIdCategoríaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdCategoríaKeyTyped
        char caracter = evt.getKeyChar();
        if(this.jTextFieldIdCategoría.getText().length() == 5 || !Character.isDigit(caracter)) 
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldIdCategoríaKeyTyped

    private void jTextFieldNombreCategoríaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreCategoríaKeyTyped
        char caracter = evt.getKeyChar();
        if(this.jTextFieldNombreCategoría.getText().length() == 50 || !(Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE)) 
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNombreCategoríaKeyTyped

    private void jTextFieldIniciarSesionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIniciarSesionUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIniciarSesionUsuarioActionPerformed

    private void jButtonIniciarSesionLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionLoginActionPerformed
        // TODO add your handling code here:
        validarLogin();

    }//GEN-LAST:event_jButtonIniciarSesionLoginActionPerformed

    private void jPasswordFieldIniciarSesionPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldIniciarSesionPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldIniciarSesionPasswordActionPerformed

    private void jButtonAgregarFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarFabricantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarFabricantesActionPerformed

    private void jTextFieldIdNombreFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdNombreFabricantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdNombreFabricantesActionPerformed

    private void jTextFieldIdFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdFabricantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdFabricantesActionPerformed

    private void Menu_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_IniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_IniciarSesionActionPerformed

    private void jTextFieldIdCategoría1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdCategoría1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdCategoría1ActionPerformed

    private void jTextFieldIdCategoría1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdCategoría1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdCategoría1KeyTyped

    private void jTextFieldNombreCategoría1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreCategoría1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreCategoría1KeyTyped

    private void jButtonAgregarCategoría1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarCategoría1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarCategoría1ActionPerformed

    private void jButtonLimpiarCategoría1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarCategoría1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarCategoría1ActionPerformed
    
    private void inicioApp(){
        this.setExtendedState(MAXIMIZED_BOTH);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = this.Frame_IniciarSesion.getSize();
        this.Frame_IniciarSesion.setLocation((pantalla.width-ventana.width)/2, (pantalla.height-ventana.height)/2);
        this.Frame_IniciarSesion.setVisible(true);
        
        this.Frame_ListaFabricantes.setVisible(false);
        this.Frame_EditarFabricantes.setVisible(false);
        this.Frame_ListarCategorias.setVisible(false);
        this.Frame_EditarCategorias.setVisible(false);
        this.Frame_ListarBicicletas.setVisible(false);
        this.Frame_EditarBicicletas.setVisible(false);
        this.Frame_acercaDe.setVisible(false);
        
        this.Menu_IniciarSesion.setEnabled(true);
        this.Menu_CerrarSesion.setEnabled(false);
        this.Menu_Salir.setEnabled(true);
        
        this.jMenu_Fabricantes.setEnabled(false);
        this.jMenu_Bicicletas.setEnabled(false);
        this.jMenu_Categorias.setEnabled(false);
    }
    
    
    /*******************************************************
     * FORMULARIO LOGIN
     *******************************************************/
    
    private void validarLogin(){
        String username = this.jTextFieldIniciarSesionUsuario.getText();
        String password = String.valueOf(this.jPasswordFieldIniciarSesionPassword.getPassword());
        Usuario u = cu.read(username);
        if(u != null){
            if(u.getUsuario().equals(username) && u.getPassword().equals(password)){
                JOptionPane.showMessageDialog(this, "Login Existoso! Bienvenido " + username, "Mensajes", JOptionPane.INFORMATION_MESSAGE);
                
            }else{
                    JOptionPane.showMessageDialog(this, "Acceso denegado!", "Mensajes", JOptionPane.ERROR_MESSAGE);
                }
            /////////////////////////////////////////////////////////////////////////////////////////
        }else{
            JOptionPane.showMessageDialog(this, "Acceso denegado!", "Mensajes", JOptionPane.ERROR_MESSAGE);
            
        }
    }
    
    /*******************************************************
     * FORMULARIO REGISTRO CATEGORIAS
     *******************************************************/
    private void limpiarFormularioRegistroCategorias(){
        this.jTextFieldIdCategoría.setText("");
        this.jTextFieldNombreCategoría.setText("");
        this.jTextFieldIdCategoría.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame Frame_EditarBicicletas;
    private javax.swing.JInternalFrame Frame_EditarCategorias;
    private javax.swing.JInternalFrame Frame_EditarFabricantes;
    private javax.swing.JInternalFrame Frame_IniciarSesion;
    private javax.swing.JInternalFrame Frame_ListaFabricantes;
    private javax.swing.JInternalFrame Frame_ListarBicicletas;
    private javax.swing.JInternalFrame Frame_ListarCategorias;
    private javax.swing.JInternalFrame Frame_acercaDe;
    private javax.swing.JMenu MENU_PERFIL;
    private javax.swing.JMenuItem Menu_AcercaDe;
    private javax.swing.JMenu Menu_Ayuda;
    private javax.swing.JMenu Menu_Categorias;
    private javax.swing.JMenuItem Menu_CerrarSesion;
    private javax.swing.JMenuItem Menu_IniciarSesion;
    private javax.swing.JMenuItem Menu_ListarBicilcetas;
    private javax.swing.JMenuItem Menu_ListarCategorias;
    private javax.swing.JMenuItem Menu_Salir;
    private javax.swing.JTable Tabla_RegistarBicicletaas;
    private javax.swing.JTable Tabla_RegistarCategoriaas;
    private javax.swing.JTable Tabla_RegistarFabricantees;
    private javax.swing.JButton jButtonAgregarCategoría;
    private javax.swing.JButton jButtonAgregarCategoría1;
    private javax.swing.JButton jButtonAgregarFabricantes;
    private javax.swing.JButton jButtonEliminarCategoría;
    private javax.swing.JButton jButtonEliminarCategoría1;
    private javax.swing.JButton jButtonEliminarFabricantes;
    private javax.swing.JButton jButtonIniciarSesionLogin;
    private javax.swing.JButton jButtonLimpiarCategoría;
    private javax.swing.JButton jButtonLimpiarCategoría1;
    private javax.swing.JButton jButtonLimpiarFabricantes;
    private javax.swing.JButton jButtonModificarCategoría;
    private javax.swing.JButton jButtonModificarCategoría1;
    private javax.swing.JButton jButtonModificarFabricantes;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabelIdCategoría1;
    private javax.swing.JLabel jLabelIdFabricantes;
    private javax.swing.JLabel jLabelIdNombreFabricante;
    private javax.swing.JLabel jLabelIniciarSesionPassword;
    private javax.swing.JLabel jLabelInicioSesionUsuario;
    private javax.swing.JLabel jLabelNombreCategoría;
    private javax.swing.JLabel jLabelNombreCategoría1;
    private javax.swing.JLabel jLabel_IngresdeID_Categorias;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenu_Bicicletas;
    private javax.swing.JMenu jMenu_Categorias;
    private javax.swing.JMenu jMenu_Fabricantes;
    private javax.swing.JMenuItem jMenu_ListaFabricantes;
    private javax.swing.JMenuItem jMenu_Mbicicletas;
    private javax.swing.JMenuItem jMenu_Mcategoria;
    private javax.swing.JMenuItem jMenu_Mfabricantes;
    private javax.swing.JPasswordField jPasswordFieldIniciarSesionPassword;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldIdCategoría;
    private javax.swing.JTextField jTextFieldIdCategoría1;
    private javax.swing.JTextField jTextFieldIdFabricantes;
    private javax.swing.JTextField jTextFieldIdNombreFabricantes;
    private javax.swing.JTextField jTextFieldIniciarSesionUsuario;
    private javax.swing.JTextField jTextFieldNombreCategoría;
    private javax.swing.JTextField jTextFieldNombreCategoría1;
    // End of variables declaration//GEN-END:variables

    
}
